import { sendVR } from '@/gen/proto/threedoclusion/v1/service-ScanService_connectquery'
import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';


export default function ClientPage() {
    let submitOK = false
    let scanId = 111 // Should be generated by clicking on certain scan
    const [clientId, setClientId] = useState<number | undefined>(undefined);

    const {data, refetch} = useQuery(sendVR.useQuery({ clientId, scanId }));
    // TO DO: Make it so it isn't mounted at the start

    function afterSubmit(event: React.FormEvent<HTMLFormElement>) {
      event.preventDefault();
      let codeInput = document.getElementById("code") as HTMLInputElement | null;
  
      if (codeInput){
        setClientId(parseInt(codeInput.value, 10))
        submitOK = true;
      }
    }
    // Now when waiting and client clicks submit -> redirected
    // Only supposed to redirect after send to VR is clicked?
    // Won't matter when clientID is known because we won't be using the form

    const handleRedirect = () => {
        if (submitOK) {
            //fetchData()
            refetch()
            console.log(data?.feedback);
            // Pop up to close VR once OK -> redirect?
        }
    };

  return (
    <div>
      <h1>Client Page</h1>
      <form onSubmit={afterSubmit}>
        Code: <input type="text" id="code" size={20} name="code"/><br/>
        <input type="submit" value="Submit"/> 
      </form>
      <button id="redirect-button" onClick={handleRedirect}>Send to VR</button>
    </div>
  )
}
  